SACVectorRobot:
    ActorTrainingFreq: 1
    BatchSize: 32
    ClipGrad: 1.0
    Episodes: 1000000
    ExplorationParameters:
        BatchSize: 128
        Epsilon: 1.0
        EpsilonDecay: 0.999
        EpsilonMin: 0.0
        FeatureSpaceSize: 288
        ForwardModelLearningRate: 0.001
        InverseModelLearningRate: 0.001
        ScalingFactor: 0.01
        StepDown: 200
    Gamma: 0.99
    LearningRateActor: 0.0005
    LearningRateCritic: 0.0005
    LogAlpha: 0.1
    NSteps: 4
    NetworkParameters:
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: ResNet12
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: ResNet12
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: ResNet12
    PrioritizedReplay: false
    ReplayCapacity: 80000
    ReplayMinSize: 2000
    SyncMode: soft_sync
    SyncSteps: 50
    Tau: 0.01
    TrainingDescription: SAC_VisualReaching_ResNet12
    TrainingID: SAC_VisualReaching_ResNet12
    TrainingInterval: 1
ddpg:
    BatchSize: 32
    Episodes: 1000000
    Epsilon: 0.25
    ExplorationParameters:
        Epsilon: 1
        EpsilonDecay: 0.995
        EpsilonMin: 0.01
    Gamma: 0.99
    LearningRateActor: 0.0001
    LearningRateCritic: 0.0001
    NSteps: 5
    NetworkParameters:
    -   Filters: 32
        Units: 100
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    -   Filters: 32
        Units: 100
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    ReplayCapacity: 100000
    ReplayMinSize: 1000
    SyncMode: soft_sync
    SyncSteps: 50
    Tau: 0.2
    TrainingID: DDPG2D
    TrainingInterval: 64
default:
    BatchSize: 64
    DoubleLearning: true
    Episodes: 1000000
    ExplorationParameters:
        Epsilon: 1.0
        EpsilonDecay: 0.999
        EpsilonMin: 0.02
    Gamma: 0.99
    LearningRate: 0.0001
    NSteps: 5
    NetworkParameters:
    -   DuelingNetworks: false
        Filters: 32
        NoisyNetworks: true
        Units: 32
        VectorNetworkArchitecture: SmallDense
        VisualNetworkArchitecture: CNN
    ReplayCapacity: 100000
    ReplayMinSize: 1000
    SyncMode: hard_sync
    SyncSteps: 50
    Tau: 0.1
    TrainingID: Double5StepNoisyDQN_Pendulum
dqn:
    BatchSize: 32
    DoubleLearning: false
    Episodes: 1000000
    ExplorationParameters:
        Epsilon: 1.0
        EpsilonDecay: 0.995
        EpsilonMin: 0.02
    Gamma: 0.99
    LearningRate: 0.0005
    NSteps: 5
    NetworkParameters:
    -   DuelingNetworks: false
        Filters: 32
        NoisyNetworks: false
        Units: 32
        VectorNetworkArchitecture: SmallDense
        VisualNetworkArchitecture: CNN
    ReplayCapacity: 50000
    ReplayMinSize: 5000
    SyncMode: hard_sync
    SyncSteps: 200
    Tau: 0.12
    TrainingID: DQNScheduleFirstTest
    TrainingInterval: 8
sac:
    ActorNum: 1
    BatchSize: 60
    ClipGrad: 1.0
    ExplorationParameters:
        Epsilon: 0.4
        EpsilonDecay: 0.99995
        EpsilonMin: 0.01
        StepDown: false
    Gamma: 0.99
    LearningRateActor: 0.0005
    LearningRateCritic: 0.0005
    LogAlpha: -2.0
    NSteps: 4
    AdaptiveExploration: true
    NetworkUpdateFrequency: 50
    NetworkParameters:
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    PrioritizedReplay: true
    ReplayCapacity: 1000000
    ReplayMinSize: 50
    SyncMode: soft_sync
    SyncSteps: 50
    Tau: 0.01
    TrainingID: RL_ACC_TEST_v15_accel_interface_2_5_action_normalized_and_linearized_reward_control_speed_only_dense_batchsize_60_all_scenarios_V2
    TrainingInterval: 10
td3:
    ActorTrainingFreq: 3
    BatchSize: 64
    ClipGrad: 10.0
    Episodes: 1000000
    Epsilon: 0.2
    ExplorationParameters:
        Epsilon: 1.0
        EpsilonDecay: 0.9995
        EpsilonMin: 0.03
        StepDown: 0
    Gamma: 0.99
    LearningRateActor: 0.001
    LearningRateCritic: 0.001
    NSteps: 4
    NetworkParameters:
    -   Filters: 64
        Units: 64
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    -   Filters: 32
        Units: 32
        VectorNetworkArchitecture: Dense
        VisualNetworkArchitecture: CNN
    PredictionNoise: 0.2
    PredictionNoiseClip: 0.5
    PrioritizedReplay: false
    ReplayCapacity: 100000
    ReplayMinSize: 5000
    SyncMode: soft_sync
    SyncSteps: 50
    Tau: 0.04
    TrainingID: TD3_3DBall
    TrainingInterval: 64
